#!/usr/bin/env bash
# Launches a RunPod GPU pod running vLLM, serving MODEL_ID with vLLM's
# built-in Anthropic-compatible /v1/messages endpoint (in addition to its
# usual OpenAI-compatible one) — so Claude Code can talk to it directly,
# no translation proxy required.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib.sh
source "$ROOT/scripts/lib.sh"

load_env
require_runpodctl

: "${RUNPOD_API_KEY:?Set RUNPOD_API_KEY in .env}"
: "${MODEL_ID:?Set MODEL_ID in .env}"
: "${GPU_TYPE_ID:?Set GPU_TYPE_ID in .env}"
: "${VLLM_API_KEY:?Set VLLM_API_KEY in .env}"
: "${POD_NAME:=tynet-runpod-vllm}"
: "${TOOL_CALL_PARSER:=qwen3_xml}"

runpodctl config --apiKey "$RUNPOD_API_KEY" >/dev/null

ENV_JSON="{\"VLLM_API_KEY\":\"$VLLM_API_KEY\""
if [ -n "${HF_TOKEN:-}" ] && [ "$HF_TOKEN" != "REPLACE_ME_OPTIONAL" ]; then
  ENV_JSON="$ENV_JSON,\"HF_TOKEN\":\"$HF_TOKEN\""
fi
ENV_JSON="$ENV_JSON}"

# vllm/vllm-openai's image ENTRYPOINT is ["vllm", "serve"], so --docker-args
# here is exactly the argument list to `vllm serve`.
DOCKER_ARGS="$MODEL_ID --host 0.0.0.0 --port 8000 --api-key $VLLM_API_KEY --enable-auto-tool-choice --tool-call-parser $TOOL_CALL_PARSER --max-model-len 65536"

CREATE_CMD=($(runpodctl_create_cmd))

echo "Creating pod '$POD_NAME' ($GPU_TYPE_ID, model $MODEL_ID)..." >&2

OUTPUT="$(runpodctl "${CREATE_CMD[@]}" \
  --name "$POD_NAME" \
  --image "vllm/vllm-openai:latest" \
  --gpu-id "$GPU_TYPE_ID" \
  --gpu-count 1 \
  --cloud-type SECURE \
  --container-disk-in-gb 20 \
  --volume-in-gb 80 \
  --volume-mount-path /root/.cache/huggingface \
  --ports "8000/http,22/tcp" \
  --env "$ENV_JSON" \
  --docker-args "$DOCKER_ARGS")"

echo "$OUTPUT"

POD_ID=""
if command -v jq >/dev/null 2>&1; then
  POD_ID="$(echo "$OUTPUT" | jq -r '.id // .podId // empty' 2>/dev/null || true)"
fi
if [ -z "$POD_ID" ] && command -v python3 >/dev/null 2>&1; then
  POD_ID="$(echo "$OUTPUT" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
    print(d.get("id") or d.get("podId") or "")
except Exception:
    pass
' 2>/dev/null || true)"
fi

if [ -z "$POD_ID" ]; then
  echo "" >&2
  echo "Couldn't auto-detect the pod ID from the output above." >&2
  echo "Find it with 'runpodctl $(runpodctl_get_cmd) list' or the RunPod console," >&2
  echo "then run: echo POD_ID=<id> >> \"$ROOT/.runpod-pod.env\"" >&2
  exit 0
fi

BASE_URL="https://${POD_ID}-8000.proxy.runpod.net"

cat > "$ROOT/.runpod-pod.env" <<EOF
# Generated by scripts/deploy-pod.sh — not managed by 1Password.
POD_ID=$POD_ID
ANTHROPIC_BASE_URL=$BASE_URL
EOF

echo "" >&2
echo "Pod created: $POD_ID" >&2
echo "Base URL:    $BASE_URL" >&2
echo "" >&2
echo "vLLM needs a minute or two to download weights and start serving." >&2
echo "Check readiness with:" >&2
echo "  curl -s $BASE_URL/health" >&2
echo "" >&2
echo "Then run scripts/configure-claude-code.sh to point Claude Code at it." >&2
